source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-archives"
gem "jekyll-email-protect"
gem "jekyll-feed"
gem "jekyll-get-json"
gem "jekyll-imagemagick"
gem "jekyll-jupyter-notebook"
gem "jekyll-link-attributes"
gem "jekyll-minifier"
gem "jekyll-paginate-v2"
gem "jekyll-scholar"
gem "jekyll-sitemap"
gem "jekyll-toc"
gem "jekyll-twitter-plugin"
gem "jemoji"
gem "mini_racer"
gem "nokogiri"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-archives"
  gem "jekyll-paginate-v2"
end
